### DISCUSSION TITLE
How to handle region specific variations for a single environment?

### DISCUSSION THREAD

**Discussion by v-kumar** [palkan/anyway_config#154] [General]
AnywayConfig has been working great for us.

We have a multi-region deployment. For example, staging or production environment could have different values for a small number of configurations based on their region of deployment.

95% of the configuration values are the same, except for a few region specific changes. Also, they are considered the same "environment", i.,e production or staging and not "production-eu", etc.

```
production:
  eu:
    default_locale: en_uk
  us:
    default_locale: en_us
  <all other settings>:
```

Is there a way to merge multiple sources for a single environment? i..,e similar to how `local` can merge with `development`, is there a way to merge production-eu values to production?
