### ISSUE TITLE
Can't use with Rails Credentials

### ISSUE THREAD

**Issue by Quintasan** [palkan/anyway_config#39]
I created a brand new application using Rails 5. To my `config/application.rb` I added the following code:
```ruby
# config/application.rb
module Poloris
  class Config < Anyway::Config
    attr_config(
      database_host: 'localhost',
      database_port: 5432,
      database_user: 'root',
      database_password: 'debiru'
    )
  end

  def self.config
    @config ||= Config.new
  end
  class Application < Rails::Application
    ...
  end
end
```
in my credentials I added:
```yaml
poloris:
  secret_key_base: 93d324c53f5cdd193349aec6e97191d502d34ecedbb44cac1aac51ee62dd2ca18d3c18b110781bdb6416c6ae1acdde1a49600cb5d4bdd66a5277eabcb7f9ff05
  database_host: 'localhost'
  database_port: 5432
  database_user: 'debiru'
  database_password: 'debiru'
```
but when I try doing `AnywayConfig.for(:poloris)` I get: 
```ruby
irb(main):001:0> Anyway::Config.for(:poloris)
Traceback (most recent call last):
        1: from (irb):1
TypeError (no implicit conversion of nil into Hash)
```

What am I doing wrong?
